import { Post, Trend, TrendPost } from "./types";
import { subHours, subMinutes } from "date-fns";

const now = new Date();

export const mockTrends: Trend[] = [
  {
    id: "trend-1",
    niche: "ai-tools",
    cluster_label: "Local LLM Execution & Inference",
    representative_title: "Ollama: Get up and running with Llama 3, Mistral, and other large language models locally",
    trend_score: 94.5,
    growth_rate: 2.3,
    engagement_velocity: 450.2,
    cross_platform_count: 3,
    posting_frequency: 12,
    post_count: 12,
    platforms: ["github", "hackernews", "reddit"],
    window_start: subHours(now, 24).toISOString(),
    window_end: now.toISOString(),
    created_at: now.toISOString(),
  },
  {
    id: "trend-2",
    niche: "ai-tools",
    cluster_label: "AI Code Assistants & Agents",
    representative_title: "Devin - The first AI software engineer",
    trend_score: 88.2,
    growth_rate: 1.8,
    engagement_velocity: 320.5,
    cross_platform_count: 4,
    posting_frequency: 8,
    post_count: 8,
    platforms: ["github", "producthunt", "hackernews", "devto"],
    window_start: subHours(now, 24).toISOString(),
    window_end: now.toISOString(),
    created_at: now.toISOString(),
  },
  {
    id: "trend-3",
    niche: "ai-tools",
    cluster_label: "Vector Databases & RAG",
    representative_title: "Chroma: the open-source embedding database",
    trend_score: 76.4,
    growth_rate: 1.2,
    engagement_velocity: 180.9,
    cross_platform_count: 2,
    posting_frequency: 5,
    post_count: 5,
    platforms: ["github", "hackernews"],
    window_start: subHours(now, 24).toISOString(),
    window_end: now.toISOString(),
    created_at: now.toISOString(),
  }
];

export const mockPosts: Post[] = [
  {
    id: "post-1",
    source_id: "src-1",
    platform: "github",
    niche: "ai-tools",
    title: "ollama/ollama",
    caption: "Get up and running with Llama 3, Mistral, Gemma, and other large language models.",
    url: "https://github.com/ollama/ollama",
    creator: "ollama",
    hashtags: ["go", "c++"],
    engagement_count: 65430,
    engagement_breakdown: { stars_today: 450, forks: 4320 },
    rank_position: 1,
    velocity_score: 450.0,
    posted_at: null,
    scraped_at: subMinutes(now, 5).toISOString(),
  },
  {
    id: "post-2",
    source_id: "src-2",
    platform: "hackernews",
    niche: "ai-tools",
    title: "Show HN: I built a local AI agent that writes code",
    caption: null,
    url: "https://news.ycombinator.com/item?id=123456",
    creator: "aicoder99",
    hashtags: [],
    engagement_count: 342,
    engagement_breakdown: { comments: 120 },
    rank_position: 4,
    velocity_score: 85.5,
    posted_at: subHours(now, 4).toISOString(),
    scraped_at: subMinutes(now, 10).toISOString(),
  },
  {
    id: "post-3",
    source_id: "src-3",
    platform: "producthunt",
    niche: "ai-tools",
    title: "Devika",
    caption: "An open-source AI software engineer",
    url: "https://producthunt.com/posts/devika",
    creator: "stitionai",
    hashtags: ["artificial-intelligence", "developer-tools"],
    engagement_count: 890,
    engagement_breakdown: { comments: 45 },
    rank_position: 1,
    velocity_score: 890.0,
    posted_at: subHours(now, 12).toISOString(),
    scraped_at: subMinutes(now, 2).toISOString(),
  }
];
